trigger:
- main

pool:
  name: Default

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'


- script: terraform version

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    commandOptions: '-migrate-state'
    backendServiceArm: 'class_pipleline'
    backendAzureRmResourceGroupName: 'DoNotDeleteRg'
    backendAzureRmStorageAccountName: 'donotdeletestorage555'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'terraformclass.tfstate'