name: Test Self-hosted Runner

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - main

jobs:
  test:
    runs-on: [self-hosted, Dhananjay-GH]
    steps:
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        run: echo "Terraform version"
